version: '3'

services:
  # MySQL
  db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: zydb
      MYSQL_USER: zouying
      MYSQL_PASSWORD: 123456
    volumes:
      - ./container-data:/var/lib/mysql
      - ./container-log:/var/log/mysql
    ports:
      - '13306:3306'
